Adds Bls.key_validate
lambdaclass/lambda_ethereum_consensus pull request #1016
Opened 2024-04-22 14:45 UTC by guha-rahul

**Motivation**

**Description**

Closes #836 

Please let me know if further changes need to be done if I made a mistake or missed something.

2024-04-22 15:10 UTC, MegaRedHand requested changes
Great work! Can you add some unit tests in `test/unit/bls_test.exs` for these changes?

2024-04-22 18:43 UTC, MegaRedHand reviewed
The Rust code is failing to compile ([here's the log](https://github.com/lambdaclass/lambda_ethereum_consensus/actions/runs/8787985345/job/24117486014?pr=1016)). Also, there are some linter errors.

2024-04-22 18:43 UTC, MegaRedHand commented on test/unit/bls_test.exs
> +    >>
Nit: this can be written as `<<0::384>>`

2024-04-22 18:43 UTC, MegaRedHand commented on test/unit/bls_test.exs
> +  alias Bls.key_validate, as: key_validate
We don't import functions like this, since the module name adds a lot of context.

```suggestion
```

2024-04-22 18:43 UTC, MegaRedHand commented on test/unit/bls_test.exs
> +      >>
Seems the formatter doesn't like this. I suggest you hex-encode this and use [`Base.decode16!/2`](https://hexdocs.pm/elixir/1.16.2/Base.html#decode16!/2) for loading the pubkey.

2024-04-22 21:24 UTC, guha-rahul commented
added the necessary changes!

2024-04-23 13:17 UTC, MegaRedHand reviewed
There are some formatting errors ([here's the log](https://github.com/lambdaclass/lambda_ethereum_consensus/actions/runs/8791118491/job/24124780076?pr=1016))

2024-04-23 13:20 UTC, guha-rahul commented
Those should be solved by `make fmt` right?

2024-04-23 13:30 UTC, MegaRedHand commented
Yes

2024-04-23 13:59 UTC, guha-rahul commented
i am just curious even tho i worked with 4 files why did I got formatting errors in 17 files?

2024-04-23 15:27 UTC, MegaRedHand commented
I'm not really sure, but somehow your `mix format` is stricter than the one we're using.

2024-04-23 15:31 UTC, guha-rahul commented
any suggestions on how to make it less strict? 
Also thank you Tomás for helping me contribute, really grateful for it.

2024-04-23 15:55 UTC, mpaulucci approved these changes
LGTM

2024-04-23 15:57 UTC, MegaRedHand commented
Not really, but checking your working environment might help. Did you install all the dependencies via `asdf`? `mix --version` is also 1.16.2 ?

Also, since this conversation is unrelated to the PR, I suggest we continue it in the [telegram group](https://t.me/lambdaconsensus).

2024-04-23 15:58 UTC, MegaRedHand approved these changes
Thanks for your contribution, and congrats on your first merged PR on this repo!

2024-04-23 15:58 UTC, merged

2024-04-23 16:00 UTC, MegaRedHand commented
@all-contributors please add @guha-rahul for code