refactor: Libp2pPort gossip as callbacks instead of pids
lambdaclass/lambda_ethereum_consensus pull request #1111
Opened 2024-05-27 19:06 UTC by avilagaston9

**Motivation**

In our current implementation, we redirect gossip messages using the PIDs of the consumers. This forces us to have one process per handler. 

**Description**
- Change the dispatch algorithm to use module names instead.
- Make the consumers implement a `handle_gossip_message` behavior.

Closes #1108

2024-05-27 21:42 UTC, MegaRedHand commented on lib/libp2p_port.ex
> +  @spec subscribe_to_topic(GenServer.server(), String.t(), atom()) :: :ok | {:error, String.t()}
```suggestion
  @spec subscribe_to_topic(GenServer.server(), String.t(), module()) :: :ok | {:error, String.t()}
```

2024-05-27 21:42 UTC, MegaRedHand commented on lib/libp2p_port.ex
> +    GenServer.cast(__MODULE__, {:new_subscriptor, String.to_atom(topic_name), module})
This should send the message to `pid` instead of `__MODULE__`. With that we can re-add the removed tests.

2024-05-28 15:58 UTC, Arkenan requested changes

2024-05-28 15:58 UTC, Arkenan commented on test/unit/libp2p_port_test.exs
> +      :ok = Libp2pPort.publish(:publisher, topic, message)
We don't need the spawn link anymore. This publish can be called right after the subscribe call.

2024-05-28 15:58 UTC, Arkenan commented on test/unit/libp2p_port_test.exs
> +    # The message sent is the pid
Let's explain why we do this (we use the message in this module's handler to decode the pid and send a notification)

2024-05-29 10:28 UTC, Arkenan approved these changes

2024-05-29 10:29 UTC, merged