replace `BlockStore` and `StateStore` with `BlockDb` and `StateDb`
lambdaclass/lambda_ethereum_consensus pull request #750
Opened 2024-02-14 12:30 UTC by manojkgorle

**Motivation**

**Description**

Closes #686

2024-02-14 15:34 UTC, MegaRedHand commented
The CI is failing due to unordered import lists in some places.

2024-02-14 16:34 UTC, manojkgorle commented
I have fixed them now. let me know if there are any changes to make.

2024-02-14 17:27 UTC, MegaRedHand commented
Please sync with main

2024-02-15 07:18 UTC, manojkgorle commented
Synced with main.

2024-02-15 13:49 UTC, MegaRedHand requested changes
There is an old code fragment that should be removed. Also, don't forget you can run `make lint` locally to check the `CI / lint` job's output.

2024-02-15 13:49 UTC, MegaRedHand commented on lib/lambda_ethereum_consensus/beacon/beacon_node.ex
> +    BlockDb.get_block(block_root)
```suggestion
```

2024-02-15 16:26 UTC, manojkgorle commented
updated to main.

2024-02-15 18:35 UTC, MegaRedHand approved these changes
Thanks for your contribution! 😄

2024-02-15 18:36 UTC, merged

2024-02-15 19:21 UTC, MegaRedHand commented
@all-contributors please add @manojkgorle for code